version: '3.7'
services:
    mongo:
        ports:
            - 27017:27017
    app:
        ports:
            - ${API_PORT}:${API_PORT}
            - 9229:9229
        volumes:
            - '.:/app/'
        command: npx nodemon --delay 1000ms --inspect=0.0.0.0:9229 -w ./packages/api/dist ./packages/api/dist/api-server.js
    decorator:
        ports:
            - ${DECORATOR_PORT}:${DECORATOR_PORT}
        volumes:
            - '.:/app/'
        command: npx nodemon --delay 1000ms -w ./packages/decorators/dist ./packages/decorators/dist/decorator-server.js
    builder:
        build:
            context: .
            target: dev-builder
        command: npm run build:docker
        volumes:
            - '.:/app'
        expose:
            - ${WEBPACK_PORT}
        ports:
            - ${WEBPACK_PORT}:${WEBPACK_PORT}
        environment:
            - WEBPACK_PORT=${WEBPACK_PORT}
            - STATIC_ASSET_SERVER=http://static:${STATIC_PORT}/
            - API_SERVER=http://app:${API_PORT}/
    static:
        depends_on:
            - builder
        volumes:
            - '.:/app'
        environment:
            - APP_ROOT=/app/dist/web #This may be a bit of a hack. It can go away if mounting a subdirectory of a named volume becomes a thing
