version: '3.7'
services:
    mongo:
        ports:
            - 27017:27017
    app:
        ports:
            - ${API_PORT}:${API_PORT}
            - 9229:9229
        volumes:
            - 'app:/app/'
        command: npx nodemon --delay 1000ms --inspect=0.0.0.0:9229 --on-change-only -w ./backend ./backend/api-service.bundle.js
    decorator:
        ports:
            - ${DECORATOR_PORT}:${DECORATOR_PORT}
        volumes:
            - 'app:/app/'
        command: npx nodemon --delay 1000ms --on-change-only -w ./backend ./backend/decorator-service.bundle.js
    builder:
        build:
            context: .
            target: dev-builder
        command: npm run build:docker:watch
        volumes:
            - '.:/app'
            - 'app:/app/dist'
    static:
        volumes:
            - 'app:/app'
        environment:
            - APP_ROOT=/app/web #This may be a bit of a hack. It can go away if mounting a subdirectory of a named volume becomes a thing
volumes:
    app:
