version: "3.7"
services:
  postgres:
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=guest
      - POSTGRES_USER=guest
      - POSTGRES_DB=xsrt
    build:
      context: .
      dockerfile: ./conf/postgres/postgres.Dockerfile
  api:
    ports:
      - ${API_PORT}:8080
    volumes:
      - stored-files:${STORAGE_LOCATION}
    environment:
      - ELASTIC_HOST=http://elastic:9200
      - RABBIT_HOST=rabbit
      - API_PORT=8080
      - STORAGE_LOCATION=${STORAGE_LOCATION}
      - DB_HOST=postgres
      - DB_USER=guest
      - DB_PASSWORD=guest
    build:
      context: .
      target: api
  decorator:
    volumes:
      - stored-files:${STORAGE_LOCATION}
    environment:
      - DECORATOR_PORT=8080
      - STORAGE_LOCATION=${STORAGE_LOCATION}
      - API_HOST=http://api:${API_PORT}
      - RABBIT_HOST=rabbit
      - ELASTIC_HOST=http://elastic:9200
      - DB_HOST=postgres
      - DB_USER=guest
      - DB_PASSWORD=guest
      - CHROME_EXECUTABLE=/usr/bin/chromium-browser
    build:
      context: .
      target: decorator
      args:
        port: "${DECORATOR_PORT}"
  static:
    ports:
      - ${STATIC_PORT}:80
    volumes:
      - ${STORAGE_LOCATION}:/app
    environment:
      - FRONTEND_HOSTNAME=${FRONTEND_HOSTNAME}
      - APP_ROOT=/app
    build:
      context: .
      dockerfile: ./conf/nginx/nginx.Dockerfile
    command: /bin/sh -c "envsubst '$${STORAGE_LOCATION},$${FRONTEND_HOSTNAME},$${API_SERVER},$${APP_ROOT}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
  rabbit:
    image: rabbitmq:3.7.12-management
    hostname: rabbit
    expose:
      - 5672
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbit-data:/var/lib/rabbitmq
  elastic:
    image: elasticsearch:7.8.0
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
  kibana:
    image: kibana:7.8.0
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
volumes:
  postgres-data:
  stored-files:
  rabbit-data:
  elastic-data:
