version: '3.7'
services:
    mongo:
        image: mongo:4.0
        volumes:
            - mongo-data:/data/db
        expose:
            - 27017
        ports:
            - 27017:27017
    app:
        expose:
            - ${API_PORT}
        ports:
            - ${API_PORT}:${API_PORT}
            - 9229:9229
        links:
            - mongo
            - decorator
        depends_on:
            - mongo
            - rabbit
        restart: unless-stopped
        environment:
            - MONGO_URL=mongodb://mongo/recordings
            - API_PORT=${API_PORT}
            - STORAGE_LOCATION=${STORAGE_LOCATION}
            - RABBIT_HOST=rabbit
            - ELASTIC_HOST=elastic:9200
        volumes:
            - '.:/app/'
            - stored-files:${STORAGE_LOCATION}
        build:
            context: .
            target: dev-api
            args:
                port: "${API_PORT}"
            dockerfile: dev.Dockerfile
        command: npx nodemon --delay 1000ms --inspect=0.0.0.0:9229 -w ./dist/backend ./dist/backend/api-server.bundle.js
    decorator:
        expose:
            - ${DECORATOR_PORT}
        ports:
            - ${DECORATOR_PORT}:${DECORATOR_PORT}
            - 9230:9230
        links:
            - mongo
        depends_on:
            - mongo
            - rabbit
        restart: unless-stopped
        environment:
            - MONGO_URL=mongodb://mongo/recordings
            - DECORATOR_PORT=${DECORATOR_PORT}
            - API_SERVER=http://app:${API_PORT}
            - RABBIT_HOST=rabbit
        volumes:
            - '.:/app/'
            - stored-files:${STORAGE_LOCATION}
        build:
            context: .
            target: dev-decorator
            args:
                port: "${DECORATOR_PORT}"
            dockerfile: dev.Dockerfile
        command: npx nodemon --delay 1000ms --inspect=0.0.0.0:9230 -w ./dist/backend ./dist/backend/decorator-server.bundle.js
    rabbit:
        image: rabbitmq:3.7.12
        hostname: rabbit
        expose:
            - 5672
        volumes:
            - rabbit-data:/var/lib/rabbitmq
    static:
        ports:
            - ${STATIC_PORT}:443
        volumes:
            - stored-files:${STORAGE_LOCATION}
            - ./secret/certs:/etc/ssl/certs
        links:
            - decorator
            - app
        environment:
            - FRONTEND_HOSTNAME=${FRONTEND_HOSTNAME}
            - STORAGE_LOCATION=${STORAGE_LOCATION}
            - API_SERVER=http://app:${API_PORT}
            - APP_ROOT=/app
        build:
            context: .
            target: dev-nginx
            dockerfile: dev.Dockerfile
        command: /bin/sh -c "envsubst '$${STORAGE_LOCATION},$${FRONTEND_HOSTNAME},$${API_SERVER},$${APP_ROOT}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
    builder:
        volumes:
            - '.:/app'
        expose:
            - ${WEBPACK_PORT}
        ports:
            - ${WEBPACK_PORT}:${WEBPACK_PORT}
        environment:
            - WEBPACK_PORT=${WEBPACK_PORT}
            - STATIC_ASSET_SERVER=https://static/
            - API_SERVER=http://app:${API_PORT}/
        build:
            context: .
            target: dev-builder
            dockerfile: dev.Dockerfile
volumes:
    mongo-data:
    stored-files:
    rabbit-data:
