version: "3.7"
services:
  postgres:
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=guest
      - POSTGRES_USER=guest
      - POSTGRES_DB=xsrt
    build:
      context: .
      dockerfile: ./conf/postgres/postgres.Dockerfile
  app:
    expose:
      - ${API_PORT}
    volumes:
      - stored-files:${STORAGE_LOCATION}
    depends_on:
      - decorator
    environment:
      - POSTGRES_URL=postgres://postgres/recordings
      - DECORATOR_URL=http://decorator:${DECORATOR_PORT}
      - API_PORT=${API_PORT}
      - STORAGE_LOCATION=${STORAGE_LOCATION}
    build:
      context: .
      target: api
      args:
        port: "${API_PORT}"
  decorator:
    expose:
      - ${DECORATOR_PORT}
    volumes:
      - stored-files:${STORAGE_LOCATION}
    environment:
      - POSTGRES_URL=postgres://postgres/recordings
      - DECORATOR_PORT=${DECORATOR_PORT}
      - API_SERVER=http://app:${API_PORT}
    build:
      context: .
      target: decorator
      args:
        port: "${DECORATOR_PORT}"
  static:
    ports:
      - ${STATIC_PORT}:80
    volumes:
      - ${STORAGE_LOCATION}:/app
    environment:
      - FRONTEND_HOSTNAME=${FRONTEND_HOSTNAME}
      - APP_ROOT=/app
    build:
      context: .
      dockerfile: ./conf/nginx/nginx.Dockerfile
    command: /bin/sh -c "envsubst '$${STORAGE_LOCATION},$${FRONTEND_HOSTNAME},$${API_SERVER},$${APP_ROOT}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
  rabbit:
    image: rabbitmq:3.7.12-management
    hostname: rabbit
    expose:
      - 5672
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbit-data:/var/lib/rabbitmq
  elastic:
    image: elasticsearch:7.8.0
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
  kibana:
    image: kibana:7.8.0
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
volumes:
  postgres-data:
  stored-files:
  rabbit-data:
  elastic-data:
