version: 2.1
executors:
    node-executor:
        docker:
            - image: circleci/node:11.0.0
        working_directory: /tmp/xsrt
jobs:
    initialize:
        executor: node-executor
        steps:
            - checkout
            - restore_cache:
                key: dependency-cache-{{ checksum "package.json"}}
            - run:
                name: Install dependencies
                command: npm run initialize
            - save_cache:
                key: dependency-cache-{{ checksum "package.json"}}
                paths:
                    - node_modules
            - persist_to_workspace:
                root: ./
                paths:
                    - node_modules
                    - packages
    test:
        executor: node-executor
        steps:
            - checkout
            - attach_workspace:
                at: ./
            - run:
                name: Unit Tests
                command: npm run test:coverage
            - run:
                name: Lint
                command: npm run lint
            - store_artifacts:
                path: coverage
                prefix: coverage
    publish:
        executor: node-executor
        steps:
            - checkout
            - attach_workspace:
                at: ./
            - add_ssh_keys:
                fingerprints:
                    - "82:0b:ae:8d:4a:f9:44:8f:a1:ac:22:d8:37:99:d9:58"
            - run:
                name: Authenticate NPM
                command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
            - run:
                name: Publish to NPM
                command: npm run publish:all
workflows:
    version: 2
    initialize_and_test:
        jobs:
            - initialize:
                filters:
                    tags:
                        only: /.*/
            - test:
                requires:
                    - initialize
                filters:
                    branches:
                        only:
                            - stable
                            - master
                    tags:
                        only: /.*/
            - publish:
                requires:
                    - test
                filters:
                    tags:
                        only: /^v.*/
                    branches:
                        ignore: /.*/
