version: 2.1
executors:
    node-executor:
        docker:
            - image: circleci/node:11.0.0
        working_directory: /tmp/xsrt
jobs:
    initialize:
        executor: node-executor
        steps:
            - checkout
            - restore_cache:
                key: dependency-cache-{{ checksum "package.json"}}
            - run:
                name: Install dependencies
                command: npm run initialize
            - save_cache:
                key: dependency-cache-{{ checksum "package.json"}}
                paths:
                    - node_modules
            - persist_to_workspace:
                root: ./
                paths:
                    - node_modules
                    - packages
    test:
        executor: node-executor
        steps:
            - checkout
            - attach_workspace:
                at: ./
            - run:
                name: Unit Tests
                command: npm run test:coverage
            - run:
                name: Lint
                command: npm run lint
            - store_artifacts:
                path: coverage
                prefix: coverage
    publish:

workflows:
    version: 2
    initialize_and_test:
        jobs:
            - initialize
            - test:
                requires:
                    - initialize
                filters:
                    branches:
                        only: master

