version: 2.1
executors:
    node-executor:
        docker:
            - image: circleci/node:11.0.0
        working_directory: /tmp/xsrt
jobs:
    initialize:
        executor: node-executor
        steps:
            - checkout
            - run:
                name: Install dependencies
                command: npm run initialize
    test:
        executor: node-executor
        steps:
            - checkout
            - run:
                name: Unit Tests
                command: npm run test
            - run:
                name: Lint
                command: npm run lint
workflows:
    version: 2
    initialize_and_test:
        jobs:
            - initialize
            - test:
                requires:
                    - initialize
                filters:
                    branches:
                        only: master

