AWSTemplateFormatVersion: 2010-09-09
Description: VPCs, subnets, and related for XSRT
# Mappings:
#   NatRegionMap:
#     us-east-1:
#       AMI: "ami-184dc970"
#     us-west-1:
#       AMI: "ami-a98396ec"
#     us-west-2:
#       AMI: "ami-290f4119"
Parameters:
  WildcardCert:
    Type: String
Resources:
  ViewerBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ["-", [xsrt-viewer, !Ref AWS::Region ]]
  ViewerBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ViewerBucket
      PolicyDocument:
        Statement:
        -
          Action:
            - "s3:GetObject"
          Effect: "Allow"
          Resource:
            !Sub arn:aws:s3:::${ViewerBucket}/*
          Principal:
            AWS: !Sub arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${StaticContentAccessIdentity}
  AssetBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ["-", [xsrt-storage, !Ref AWS::Region ]]
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
  StaticContentAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Used by cloudfront to access XSRT static assets
  ViewerDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases:
          - viewer.xsrt-app.com
        Comment: CDN for XSRT viewer site
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: "/index.html"
            ErrorCachingMinTTL: 60
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: "/index.html"
            ErrorCachingMinTTL: 60
        DefaultCacheBehavior:
          TargetOriginId: S3-xsrt-viewer
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          Compress: true
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # Cache Optimized
        Origins:
          - DomainName: !GetAtt ViewerBucket.DomainName
            Id: S3-xsrt-viewer
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${StaticContentAccessIdentity}
        CacheBehaviors:
          - TargetOriginId: S3-xsrt-viewer
            ViewerProtocolPolicy: redirect-to-https
            PathPattern: /index.html
            AllowedMethods:
              - GET
              - HEAD
            Compress: true
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad # Managed-CachingDisabled
        DefaultRootObject: index.html
        HttpVersion: http2
        IPV6Enabled: true
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: !Ref WildcardCert
          MinimumProtocolVersion: TLSv1.2_2018
          SslSupportMethod: sni-only
      Tags:
        - Key: Name
          Value: viewer-distribution
  AssetsDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases:
          - storage.xsrt-app.com
        Comment: CDN for XSRT recorded assets
        DefaultCacheBehavior:
          TargetOriginId: S3-xsrt-storage
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          Compress: true
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # Managed-CachingOptimized
        Origins:
          - DomainName: !GetAtt AssetBucket.DomainName
            Id: S3-xsrt-storage
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${StaticContentAccessIdentity}
        HttpVersion: http2
        IPV6Enabled: true
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: !Ref WildcardCert
          MinimumProtocolVersion: TLSv1.2_2018
          SslSupportMethod: sni-only
      Tags:
        - Key: Name
          Value: viewer-distribution
