AWSTemplateFormatVersion: 2010-09-09
Description: >
  This template creates the necessary resources for the rk0.xyz app
Parameters:
  HostedZoneName:
    Type: String
  Certificate:
    Type: String
  Environment:
    Type: String
  Repository:
    Type: String
Conditions:
  HasSitePrefix: !Not [!Equals [!Ref "Environment", "prod"]]
Resources:
  NetworkingResources:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./networking.yml
      Parameters:
        EnvironmentName: !Ref Environment
