AWSTemplateFormatVersion: 2010-09-09
Description: >
  This template creates the necessary resources for the rk0.xyz app
Parameters:
  WildcardCert:
    Type: String
Resources:
  NetworkingResources:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./networking.yml
  Hosting:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./hosting.yml
      Parameters:
        WildcardCert: !Ref WildcardCert
