AWSTemplateFormatVersion: 2010-09-09
Description: VPCs, subnets, and related for XSRT
Parameters:
  Environment:
    Type: String
Conditions:
  HasSitePrefix: !Not [!Equals [!Ref "Environment", "prod"]]
Resources:
  MainVPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: 10.0.0.0/16

