version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - IMAGE_TAG=$(node -p -e "require('./package.json').version")
      - IMAGE_TAG="$IMAGE_TAG-$(date +%y%m%d%H%M%S)"
      - echo Installing dependencies
      - npm run initialize
  build:
    commands:
      - echo Starting build on `date`
      - npm run build:viewer
artifacts:
  files:
    - "**/*"
  base-directory: "dist/web"
